[graph]
all-features = true
exclude-dev = false
targets = []

[advisories]
yanked = "deny"
unmaintained = "all"
ignore = []

[licenses]
confidence-threshold = 0.93
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Zlib",
    "BSL-1.0",
    "NCSA",
]
exceptions = []

[licenses.private]
ignore = true

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
workspace-default-features = "allow"
external-default-features = "allow"
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
